Update install instructions
ArasLabs/readme-template pull request #9
Opened 2019-08-01 20:41 UTC by sampoearas

- remove ref to v11

Not sure how you want to handle versioning tags on this one...

2019-08-01 21:51 UTC, EliJDonahue requested changes

2019-08-01 21:51 UTC, EliJDonahue commented on README.md
> +1. Aras Innovator installed (current released version preferred)
Let's make this a little more generic. The "current released version" might not be preferred or even supported, especially as releases update over time and projects don't keep up.
```suggestion
1. Aras Innovator installed (version ___ preferred)
```

2019-08-02 13:09 UTC, sampoearas commented
Suggestion accepted.

2019-08-02 21:19 UTC, EliJDonahue approved these changes

2019-08-05 12:54 UTC, merged